SELECT * FROM facturas;
SELECT * FROM items_facturas;

SELECT F.DNI, F.FECHA_VENTA, IFa.CANTIDAD FROM facturas F
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m/%Y') AS 'MES/AÑO', IFa.CANTIDAD FROM facturas F
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

/* Cantidad de ventas por mes para cada cliente */

SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m/%Y') AS 'MES/AÑO', 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA FROM facturas F
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
GROUP BY F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m/%Y');

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0;

   


/* Límite de ventas por cliente (Volumen en decilitros) */

SELECT * FROM tabla_de_clientes TC;

SELECT DNI, NOMBRE, VOLUMEN_DE_COMPRA FROM tabla_de_clientes TC;

-- limite de ventas por cliente y por mes de cada cliente --
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m/%Y') AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10
AS CANTIDAD_MAXIMA FROM facturas F
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m/%Y');

-- Se observa que algunos clientes superan la cantidad maxima --

-- Realizamos una subconsulta, para hallar la diferencia --

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA
 AS DIFERENCIA,
 CASE
	WHEN A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA <= 0 THEN 'Venta Válida'
    ELSE 'Venta no válida'
END AS STATUS_VENTA
 FROM (
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m/%Y') AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10
AS CANTIDAD_MAXIMA FROM facturas F
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m/%Y')) A;
/* Si la diferencia es negativa, la venta es valida */


--

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0 AND ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) > 50
AND A.MES_AÑO LIKE "%2018";



